title: About myself!
author: Zain Soherwardy
email: zsoherwardy@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
Hi guys! I'm glad you came to visit my awesome website. Making this website was very hard because I dislocated my thumb. I never really realized how hard life would be without my left thumb. Aside from that, my whole life is just running, sleeping, school, and videogames (very simple). You probably don't really care, but back in my prime, I chose the name "zsoh" as my username for all videogames and now, my friends just pickef up on that and I guess they know me as "zsoh" more than my real name. 
# social links
instagram_username: z.soh11 # DO NOT include the @ character, or else the build will fail!
snapchat_username:  z.soh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
