title: Zsoh's Life!
author: Zain Soherwardy
email: zsoherwardy@ebnet.org
theme: jekyll-theme-midnight

description: > # this means to ignore newlines until "baseurl:"
# social links
instagram_username: z.soh11 # DO NOT include the @ character, or else the build will fail!
snapchat_username:  z.soh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
